services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data

  registry:
    image: registry:latest
    container_name: registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /home/ansible/installation/kubespray/contrib/offline/registry-data:/var/lib/registry

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - /home/ansible/installation/kubespray/contrib/offline/offline-files:/usr/share/nginx/html/download
      - /home/ansible/installation/kubespray/contrib/offline/nginx.conf:/etc/nginx/nginx.conf

volumes:
  nexus-data:
    external: true
